### ISSUE TITLE
Accidental recursive call?

### ISSUE THREAD

**Issue by jmandel** [the-commons-project/smart-health-card-verifier#80]
https://github.com/the-commons-project/smart-health-card-verifier/blob/1f7ab1bd1f0445a4c76c00e29434f400a5adc911/src/services/helpers/getIssuerData.ts#L34

I'm guessing only the legacy method has been tested so far, and this call *should* be to `_getIssuerData` (with an underscore in front)?

**Comment by cp-yfukuda** [comment]
Thanks for pointing that out!
Yes as you guess, when we support the legacy, we missed testing the new server access.
Issue is [fixed](https://github.com/the-commons-project/smart-health-card-verifier/commit/98d6fbdb57e1b2fee17a65ad5418d04cbb328e67).
